{
    "DWF": {
        "references": [
            "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2021-3522",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1954761",
            "https://www.suse.com/security/cve/CVE-2021-3522/"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "secalert@redhat.com",
            "ID": "CVE-2021-3522",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "GStreamer",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "All GStreamer version before 1.18.4"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "GStreamer before 1.18.4 may perform an out-of-bounds read when handling certain ID3v2 tags."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "CWE-125"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1954761",
                    "refsource": "MISC",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1954761"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "secalert@redhat.com",
                "ID": "CVE-2021-3522"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "GStreamer before 1.18.4 may perform an out-of-bounds read when handling certain ID3v2 tags."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1954761",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1954761"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-06-02T15:17Z",
        "publishedDate": "2021-06-02T15:15Z"
    }
}