{
    "DWF": {
        "references": [
            "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-10729",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1831089",
            "https://www.whitesourcesoftware.com/vulnerability-database/CVE-2020-10729",
            "https://www.suse.com/security/cve/CVE-2020-10729/",
            "https://access.redhat.com/security/cve/CVE-2020-10729"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "secalert@redhat.com",
            "ID": "CVE-2020-10729",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "Ansible",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "ansible-engine 2.9.6"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "A flaw was found in the use of insufficiently random values in Ansible. Two random password lookups of the same length generate the equal value as the template caching action for the same file since no re-evaluation happens. The highest threat from this vulnerability would be that all passwords are exposed at once for the file. This flaw affects Ansible Engine versions before 2.9.6."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "CWE-330"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1831089",
                    "refsource": "MISC",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1831089"
                },
                {
                    "name": "https://github.com/ansible/ansible/issues/34144",
                    "refsource": "MISC",
                    "url": "https://github.com/ansible/ansible/issues/34144"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "secalert@redhat.com",
                "ID": "CVE-2020-10729"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "A flaw was found in the use of insufficiently random values in Ansible. Two random password lookups of the same length generate the equal value as the template caching action for the same file since no re-evaluation happens. The highest threat from this vulnerability would be that all passwords are exposed at once for the file. This flaw affects Ansible Engine versions before 2.9.6."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://github.com/ansible/ansible/issues/34144",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://github.com/ansible/ansible/issues/34144"
                    },
                    {
                        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1831089",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1831089"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-05-27T19:15Z",
        "publishedDate": "2021-05-27T19:15Z"
    }
}