{
    "DWF": {
        "references": [
            "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2021-28676",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1958252"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "cve@mitre.org",
            "ID": "CVE-2021-28676",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "n/a",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "n/a"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "An issue was discovered in Pillow before 8.2.0. For FLI data, FliDecode did not properly check that the block advance was non-zero, potentially leading to an infinite loop on load."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "n/a"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos",
                    "refsource": "MISC",
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos"
                },
                {
                    "name": "https://github.com/python-pillow/Pillow/pull/5377",
                    "refsource": "MISC",
                    "url": "https://github.com/python-pillow/Pillow/pull/5377"
                },
                {
                    "name": "FEDORA-2021-77756994ba",
                    "refsource": "FEDORA",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@mitre.org",
                "ID": "CVE-2021-28676"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "An issue was discovered in Pillow before 8.2.0. For FLI data, FliDecode did not properly check that the block advance was non-zero, potentially leading to an infinite loop on load."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos"
                    },
                    {
                        "name": "https://github.com/python-pillow/Pillow/pull/5377",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://github.com/python-pillow/Pillow/pull/5377"
                    },
                    {
                        "name": "FEDORA-2021-77756994ba",
                        "refsource": "FEDORA",
                        "tags": [],
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-06-03T03:15Z",
        "publishedDate": "2021-06-02T16:15Z"
    }
}