{
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "psirt@us.ibm.com",
            "DATE_PUBLIC": "2021-05-28T00:00:00",
            "ID": "CVE-2020-4561",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "Cognos Analytics",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "11.0"
                                            },
                                            {
                                                "version_value": "11.1"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "IBM"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "IBM Cognos Analytics 11.0 and 11.1 DQM API allows submitting of all control requests in unauthenticated sessions. This allows a remote attacker who can access a valid CA endpoint to read and write files to the Cognos Analytics system. IBM X-Force ID: 183903."
                }
            ]
        },
        "impact": {
            "cvssv3": {
                "BM": {
                    "A": "H",
                    "AC": "L",
                    "AV": "N",
                    "C": "H",
                    "I": "H",
                    "PR": "N",
                    "S": "C",
                    "SCORE": "10.000",
                    "UI": "N"
                },
                "TM": {
                    "E": "U",
                    "RC": "C",
                    "RL": "O"
                }
            }
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "Gain Access"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://www.ibm.com/support/pages/node/6451705",
                    "refsource": "CONFIRM",
                    "title": "IBM Security Bulletin 6451705 (Cognos Analytics)",
                    "url": "https://www.ibm.com/support/pages/node/6451705"
                },
                {
                    "name": "ibm-cognos-cve20204561-command-exec (183903)",
                    "refsource": "XF",
                    "title": "X-Force Vulnerability Report",
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/183903"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "psirt@us.ibm.com",
                "ID": "CVE-2020-4561"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "IBM Cognos Analytics 11.0 and 11.1 DQM API allows submitting of all control requests in unauthenticated sessions. This allows a remote attacker who can access a valid CA endpoint to read and write files to the Cognos Analytics system. IBM X-Force ID: 183903."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://www.ibm.com/support/pages/node/6451705",
                        "refsource": "CONFIRM",
                        "tags": [],
                        "url": "https://www.ibm.com/support/pages/node/6451705"
                    },
                    {
                        "name": "ibm-cognos-cve20204561-command-exec (183903)",
                        "refsource": "XF",
                        "tags": [],
                        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/183903"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-06-01T14:33Z",
        "publishedDate": "2021-06-01T14:15Z"
    }
}