{
    "DWF": {
        "references": [
            "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2021-32490",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1943693",
            "https://www.suse.com/security/cve/CVE-2021-32490/",
            "https://ubuntu.com/security/CVE-2021-32490",
            "https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-32490",
            "https://security.archlinux.org/CVE-2021-32490"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "patrick@puiterwijk.org",
            "ID": "CVE-2021-32490",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "djvulibre",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "djvulibre-3.5.28 and earlier"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "A flaw was found in djvulibre-3.5.28 and earlier. An out of bounds write in function DJVU::filter_bv() via crafted djvu file may lead to application crash and other consequences."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "CWE-119"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1943693",
                    "refsource": "MISC",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1943693"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "security@elastic.co",
                "ID": "CVE-2021-32490"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "A flaw was found in djvulibre-3.5.28 and earlier. An out of bounds write in function DJVU::filter_bv() via crafted djvu file may lead to application crash and other consequences."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1943693",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1943693"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-06-24T19:23Z",
        "publishedDate": "2021-06-24T19:15Z"
    }
}