{
    "DWF": {
        "references": [
            "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2021-32493",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1943690",
            "https://www.suse.com/security/cve/CVE-2021-32493/",
            "https://ubuntu.com/security/CVE-2021-32493",
            "https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-32493",
            "https://security.archlinux.org/CVE-2021-32493"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "patrick@puiterwijk.org",
            "ID": "CVE-2021-32493",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "djvulibre",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "djvulibre-3.5.28 and earlier"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "A flaw was found in djvulibre-3.5.28 and earlier. A heap buffer overflow in function DJVU::GBitmap::decode() via crafted djvu file may lead to application crash and other consequences."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "CWE-119"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1943690",
                    "refsource": "MISC",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1943690"
                }
            ]
        }
    }
}