{
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "patrick@puiterwijk.org",
            "ID": "CVE-2021-32613",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "radare2",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "radare2 versions before and including 5.3.0"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "In radare2 through 5.3.0 there is a double free vulnerability in the pyc parse via a crafted file which can lead to DoS."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "CWE-416"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1959939",
                    "refsource": "MISC",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1959939"
                },
                {
                    "name": "https://github.com/radareorg/radare2/issues/18679",
                    "refsource": "MISC",
                    "url": "https://github.com/radareorg/radare2/issues/18679"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "security@elastic.co",
                "ID": "CVE-2021-32613"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "In radare2 through 5.3.0 there is a double free vulnerability in the pyc parse via a crafted file which can lead to DoS."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://github.com/radareorg/radare2/issues/18679",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://github.com/radareorg/radare2/issues/18679"
                    },
                    {
                        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1959939",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1959939"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-05-14T13:17Z",
        "publishedDate": "2021-05-14T13:15Z"
    }
}